name: task1
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8.18
  - pip
  - ninja
  - numpy=1.24.4
  - scipy=1.10.1
  - cudatoolkit=11.8.0
  - gcc_linux-64=11.4.0
  - gxx_linux-64=11.4.0
  - pytorch=2.0.0
  - torchvision=0.15.0
  - pytorch-cuda=11.8
  - pip:
      - plyfile
      - opencv-python
      - matplotlib
      - open3d==0.19.0
      - mediapy
      - lpips
      - scikit-image
      - tqdm
      - trimesh
      - tensorboard
      - wandb
      - swanlab
      - lightning==2.3.3
      - omegaconf==2.3.0
      - jaxtyping
      - typeguard
      - diffusers==0.19.3
      - transformers==4.28.1
      - accelerate
      - xformers==0.0.20
      - bitsandbytes==0.41.3
      - sentencepiece
      - safetensors
      - huggingface_hub==0.23.5
      - einops
      - kornia
      - taming-transformers-rom1504
      - open-clip-torch
      - controlnet_aux
      - nerfacc==0.5.2
      - envlight==0.1.0
      - libigl
      - xatlas
      - pysdf
      - PyMCubes
      - torchmetrics
      - rembg
      - carvekit-colab
      - onnxruntime
      - pymatting
      - pooch
      - timm
      - easydict
      - termcolor
      - torch-ema
      - rich
      - dearpygui
      - gdown
      - pymeshlab
      - Cython
      - antlr4-python3-runtime==4.9.3
